auto: false
defaults:
  author: Jonathan Knapp
description: "Hi, I'm Jon Knapp. I'm a web developer, digital consultant, community web advocate, and gamer."
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
future: false
markdown: rdiscount
paginate: 10
permalink: /:year/:month/:title
rdiscount extensions: [smart]
title: "Hi, I'm Jon Knapp."
url: jonknapp.com